#!/usr/bin/env bash
# Dotfiles and environment variables repository.
# @file The dotfiles utility tools entrypoint.
# @author Rodrigo Siqueira <me@rodriados.com>
# @copyright 2026-present Rodrigo Siqueira
set -e

SCRIPTFILE=$(realpath "$0")
SCRIPTPATH=$(cd -- "$(dirname "$SCRIPTFILE")" >/dev/null 2>&1; pwd -P)
SOURCEROOT=$(cd -- "$(dirname "$SCRIPTPATH")" >/dev/null 2>&1; pwd -P)

declare -rx SCRIPTFILE SCRIPTPATH SOURCEROOT
declare -rx DOTFILES_COMMAND_ARGUMENT="$1"

shift

# Show a help message to the user and terminate script execution.
# @param $@ The optional command to get help message for.
runhelp() {
  echo "Usage: dotfiles <command> [options]"
  echo
  echo "Dotfiles utility tools."
  echo
  echo "Commands:"
  echo "  apply             Install dotfiles from repository."
  echo "  git               Execute git in the dotfiles repository."
  echo
  echo "See 'dotfiles <command> help' to read about a specific command."
}

# Execute the selected function from the remaining command line arguments. If the
# selected function is unknown, a help message is displayed instead.
case "$DOTFILES_COMMAND_ARGUMENT" in
  apply ) bash "$SCRIPTPATH/command/apply.sh" "$@"        ;;
  git   ) bash "$SCRIPTPATH/command/git.sh" "$@"          ;;
  *     ) runhelp "$@"; exit 2                            ;;
esac
