#!/usr/bin/env bash
# Dotfiles and environment variables repository.
# @file The dotfiles utility tools entrypoint.
# @author Rodrigo Siqueira <me@rodriados.com>
# @copyright 2026-present Rodrigo Siqueira
set -e

declare -r SCRIPTPATH=$(cd -- "$(dirname "$(realpath "$0")")" >/dev/null 2>&1; pwd -P)
declare -r SOURCEROOT=$(cd -- "$(dirname "$SCRIPTPATH")" >/dev/null 2>&1; pwd -P)
declare -r DOTFILES_COMMAND_ARGUMENT="$1"

shift

# Executes the selected function from the remaining command line arguments. If the
# selected function is unknown, a help message is displayed instead.
case "$DOTFILES_COMMAND_ARGUMENT" in
  apply ) source $SCRIPTPATH/detail/apply.sh "$@"     ;;
  git   ) source $SCRIPTPATH/detail/git.sh "$@"       ;;
  *     ) cat $SCRIPTPATH/help/default.txt            ;;
esac
